### ISSUE TITLE
Mistakes in german translation

### ISSUE THREAD

**Issue by DelugeDelight** [the-abe-train/metazooa-translations#11]
Hey, 
i do not really know how to use GitHub and i apologize if this is the wrong place for this but I've noticed a few mistakes and unclarities in the german translation of the game and have tried to write a suggestion to fix them. First of all thank you to whoever worked on the german translation - it's really nice that the game is now available to more people and i hope that i can help a little bit as well. I overworked the main text to no longer include accidental word repetition, small typos and syntax errors as well as tried to make it a little closer to the english original. 

------

Main text on the front page:

Das Reich der Tiere (Metazoa, auf Griechisch) ist voll von unseren entfernten Verwandten... manche sind mit uns aber näher verwandt als andere. Im Spiel Metazooa kannst du testen, wie gut du unseren Stammbaum kennst!

Dein Ziel: Errate das heutige Rätsel-Tier mit so wenigen Versuchen wie möglich! Mit jedem Versuch kannst du das Ergebnis weiter eingrenzen, denn du siehst, welchen Teil des Stammbaums dein Tipp und das Ergebnis (Reich, Stamm, Klasse, Ordnung etc.) gemeinsam haben. Je näher du der Lösung kommst  ist, desto mehr lernst du über dein Rätsel-Tier.

Ist die Antwort beispielsweise “Mensch”, dann könnte dein angefertigter Stammbaum so aussehen:

[example tree here]

Es gibt nur ein Rätsel-Tier pro Tag zu finden, aber du hast 20 Versuche dafür! Das nächste Rätsel findest du hier dann ab [time here]

[start button here]

Du hast dein Rätsel-Tier heute schon gefunden? Los gehts! Metaflora!

-----

Also the sentence "Enter your next guess" has typo in german, it should be "nächsten" instead of "nächsen"

-----

Again, i hope this is the right place for these suggestions, if not it would be nice if someone could tell me where i should put this otherwise.

**Comment by the-abe-train** [comment]
@DelugeDelight thank you for the corrections! 

I tried add them to the `de-DE.json` file myself, but I don't understand the grammatical changes enough to re-input the key words (words in {{}} in the translation file).

Since you're not familiar with GitHub, it would help me if you could download this file, make your corrections into it, and then re-upload it here. You can follow the instructions on the README file (the "cover page" of this code repository) for guidance, and respond to me in this thread if you have any questions.

[de-DE.json](https://github.com/user-attachments/files/16737998/de-DE.json)

**Comment by DelugeDelight** [comment]
@the-abe-train thank you for the quick reply! 
Looking at the file helped a lot to understand why the german translator/s before me translated things in a certain way, sometimes the differences in grammar only leave certain options. Nonetheless i fixed some small typos and hope that the attached .json file works. Thanks for your continuous work on the games!

[De updated.json](https://github.com/user-attachments/files/16741534/De.updated.json)

**Comment by the-abe-train** [comment]
Changes have been implemented. Thank you for helping to improve the game!
