### ISSUE TITLE
Mixup between daisy and edible crysanthemum / crown daisy

### ISSUE THREAD

**Issue by mlell** [the-abe-train/metazooa-translations#6]
https://github.com/the-abe-train/metazooa-translations/blob/f9ae109889d85732a0d84ea1218ddcfcf7a9abd9/Species%20Lists/plants.json#L915-L920

~~I think two species are mixed up here~~. **EDIT**: There seems to be an unclear distinction between different flowers of the same kind, which also differ for each language. Is it besser to add two separate entries for each of them or to disambiguate to one of them?
Speaking for Germans at least, *B. perennis* and Leucanthemum are much more widely known than *G. coronaria*.

* Daisy = *Bellis perennis* = ES: Margarita = DE: Gänseblümchen
* Crown Daisy / Edible Crysanthemum = *Glebionis coronaria* = ES: ojo de buey / flor de muerto = DE: Kronenwucherblume / Speisecrysantheme
* Daisy = *Leucanthemum spp.* = ES: [Margarita, among many others](https://www.europlusmed.org/cdm_dataportal/taxon/0eb6ca37-3365-4af5-a800-8fc4b8c366fa) = DE: Margarite

**Comment by mlell** [comment]
Proposed to fix the German name (the edit was my mistake) for now (#7) even though the flower is much less known than the other two options

**Comment by the-abe-train** [comment]
Thank you! I changed the name in the game. The update will go live soon.
